version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    tty: true

  frontend:
    build:
      context: ./frontend
    ports:
      - "3101:3101"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    tty: true

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: studyrecorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data 

  