services:
  backend:
    build:
      context: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      ENV: production
    command: sh -c "npm install && npm run build && node dist/main.js"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3101:3101"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "npm install && npm run build"
