version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=docker

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3101:3101"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=docker

  